name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_PATH: caesar

jobs:
  functional-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.x"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run functional tests
        run: |
            make install
            make
            ./tests/functional/run.sh

  coding-style:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.x"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8

      - name: Check coding style
        run: flake8 ${{env.PROJECT_PATH}} --ignore E124,E128,E131,E221,E241,E302,W503 --max-line-length=80
